version: "3.7"

services:
  app:
    image: sparkymat/markit:latest
    ports:
      - "3000:3000"
    working_dir: /app
    restart: always
    environment:
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_LOG_TO_STDOUT: 1
      RAILS_ENV: production
      SECRET_KEY_BASE: foobar
      DATABASE_URL: postgres://foolsbarn:foolsbarn@db/markit?pool=5
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: foolsbarn
      POSTGRES_PASSWORD: foolsbarn
      POSTGRES_DB: markit
