// Code generated by qtc from "card.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/partial/card.qtpl:1
package partial

//line view/partial/card.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/partial/card.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/partial/card.qtpl:1
func StreamCard(qw422016 *qt422016.Writer, body string) {
//line view/partial/card.qtpl:1
	qw422016.N().S(`
  <div class="max-w-sm mx-auto flex flex-col p-6 bg-white rounded-lg shadow-lg mt-16">
    `)
//line view/partial/card.qtpl:3
	qw422016.N().S(body)
//line view/partial/card.qtpl:3
	qw422016.N().S(`
  </div>
`)
//line view/partial/card.qtpl:5
}

//line view/partial/card.qtpl:5
func WriteCard(qq422016 qtio422016.Writer, body string) {
//line view/partial/card.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/partial/card.qtpl:5
	StreamCard(qw422016, body)
//line view/partial/card.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line view/partial/card.qtpl:5
}

//line view/partial/card.qtpl:5
func Card(body string) string {
//line view/partial/card.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line view/partial/card.qtpl:5
	WriteCard(qb422016, body)
//line view/partial/card.qtpl:5
	qs422016 := string(qb422016.B)
//line view/partial/card.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line view/partial/card.qtpl:5
	return qs422016
//line view/partial/card.qtpl:5
}
