// Code generated by qtc from "input.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/partial/input.qtpl:1
package partial

//line view/partial/input.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/partial/input.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/partial/input.qtpl:1
func StreamTextInput(qw422016 *qt422016.Writer, id string, name string, placeholder string) {
//line view/partial/input.qtpl:1
	qw422016.N().S(`
  <input type="text" name="`)
//line view/partial/input.qtpl:2
	qw422016.E().S(name)
//line view/partial/input.qtpl:2
	qw422016.N().S(`" id="`)
//line view/partial/input.qtpl:2
	qw422016.E().S(id)
//line view/partial/input.qtpl:2
	qw422016.N().S(`" class="text-2xl font-light border rounded-sm shadow-inner w-full p-2 mb-3" placeholder="`)
//line view/partial/input.qtpl:2
	qw422016.E().S(placeholder)
//line view/partial/input.qtpl:2
	qw422016.N().S(`" />
`)
//line view/partial/input.qtpl:3
}

//line view/partial/input.qtpl:3
func WriteTextInput(qq422016 qtio422016.Writer, id string, name string, placeholder string) {
//line view/partial/input.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/partial/input.qtpl:3
	StreamTextInput(qw422016, id, name, placeholder)
//line view/partial/input.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line view/partial/input.qtpl:3
}

//line view/partial/input.qtpl:3
func TextInput(id string, name string, placeholder string) string {
//line view/partial/input.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line view/partial/input.qtpl:3
	WriteTextInput(qb422016, id, name, placeholder)
//line view/partial/input.qtpl:3
	qs422016 := string(qb422016.B)
//line view/partial/input.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line view/partial/input.qtpl:3
	return qs422016
//line view/partial/input.qtpl:3
}

//line view/partial/input.qtpl:5
func StreamPasswordInput(qw422016 *qt422016.Writer, id string, name string, placeholder string) {
//line view/partial/input.qtpl:5
	qw422016.N().S(`
  <input type="password" name="`)
//line view/partial/input.qtpl:6
	qw422016.E().S(name)
//line view/partial/input.qtpl:6
	qw422016.N().S(`" id="`)
//line view/partial/input.qtpl:6
	qw422016.E().S(id)
//line view/partial/input.qtpl:6
	qw422016.N().S(`" class="text-2xl font-light border rounded-sm shadow-inner w-full p-2 mb-3" placeholder="`)
//line view/partial/input.qtpl:6
	qw422016.E().S(placeholder)
//line view/partial/input.qtpl:6
	qw422016.N().S(`" />
`)
//line view/partial/input.qtpl:7
}

//line view/partial/input.qtpl:7
func WritePasswordInput(qq422016 qtio422016.Writer, id string, name string, placeholder string) {
//line view/partial/input.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/partial/input.qtpl:7
	StreamPasswordInput(qw422016, id, name, placeholder)
//line view/partial/input.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line view/partial/input.qtpl:7
}

//line view/partial/input.qtpl:7
func PasswordInput(id string, name string, placeholder string) string {
//line view/partial/input.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line view/partial/input.qtpl:7
	WritePasswordInput(qb422016, id, name, placeholder)
//line view/partial/input.qtpl:7
	qs422016 := string(qb422016.B)
//line view/partial/input.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line view/partial/input.qtpl:7
	return qs422016
//line view/partial/input.qtpl:7
}
