// Code generated by qtc from "nav.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/partial/nav.qtpl:1
package partial

//line view/partial/nav.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/partial/nav.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/partial/nav.qtpl:1
func StreamDropdown(qw422016 *qt422016.Writer, items map[string]string) {
//line view/partial/nav.qtpl:1
	qw422016.N().S(`
  <nav role="navigation" class="dropdown fixed right-4 top-4">
    <span class="material-icons 3xl">settings</span>
    <ul class="right-0 top-6">
      `)
//line view/partial/nav.qtpl:5
	for label, link := range items {
//line view/partial/nav.qtpl:5
		qw422016.N().S(`
      <a class="no-underline" href="`)
//line view/partial/nav.qtpl:6
		qw422016.E().S(link)
//line view/partial/nav.qtpl:6
		qw422016.N().S(`"><li>`)
//line view/partial/nav.qtpl:6
		qw422016.E().S(label)
//line view/partial/nav.qtpl:6
		qw422016.N().S(`</li></a>
      `)
//line view/partial/nav.qtpl:7
	}
//line view/partial/nav.qtpl:7
	qw422016.N().S(`
    </ul>
  </nav>
`)
//line view/partial/nav.qtpl:10
}

//line view/partial/nav.qtpl:10
func WriteDropdown(qq422016 qtio422016.Writer, items map[string]string) {
//line view/partial/nav.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/partial/nav.qtpl:10
	StreamDropdown(qw422016, items)
//line view/partial/nav.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line view/partial/nav.qtpl:10
}

//line view/partial/nav.qtpl:10
func Dropdown(items map[string]string) string {
//line view/partial/nav.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line view/partial/nav.qtpl:10
	WriteDropdown(qb422016, items)
//line view/partial/nav.qtpl:10
	qs422016 := string(qb422016.B)
//line view/partial/nav.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line view/partial/nav.qtpl:10
	return qs422016
//line view/partial/nav.qtpl:10
}
