// Code generated by qtc from "bookmark_home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/page/bookmark_home.qtpl:1
package page

//line view/page/bookmark_home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/page/bookmark_home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/page/bookmark_home.qtpl:1
func StreamBookmarkHome(qw422016 *qt422016.Writer) {
//line view/page/bookmark_home.qtpl:1
	qw422016.N().S(`
  <h1>Hello</h1>
`)
//line view/page/bookmark_home.qtpl:3
}

//line view/page/bookmark_home.qtpl:3
func WriteBookmarkHome(qq422016 qtio422016.Writer) {
//line view/page/bookmark_home.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/page/bookmark_home.qtpl:3
	StreamBookmarkHome(qw422016)
//line view/page/bookmark_home.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line view/page/bookmark_home.qtpl:3
}

//line view/page/bookmark_home.qtpl:3
func BookmarkHome() string {
//line view/page/bookmark_home.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line view/page/bookmark_home.qtpl:3
	WriteBookmarkHome(qb422016)
//line view/page/bookmark_home.qtpl:3
	qs422016 := string(qb422016.B)
//line view/page/bookmark_home.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line view/page/bookmark_home.qtpl:3
	return qs422016
//line view/page/bookmark_home.qtpl:3
}
