// Code generated by qtc from "new_session.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/page/new_session.qtpl:1
package page

//line view/page/new_session.qtpl:1
import "github.com/sparkymat/markit/view/partial"

//line view/page/new_session.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/page/new_session.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/page/new_session.qtpl:3
func StreamNewSession(qw422016 *qt422016.Writer) {
//line view/page/new_session.qtpl:3
	qw422016.N().S(`
  `)
//line view/page/new_session.qtpl:4
	partial.StreamCard(qw422016, sessionForm())
//line view/page/new_session.qtpl:4
	qw422016.N().S(`
`)
//line view/page/new_session.qtpl:5
}

//line view/page/new_session.qtpl:5
func WriteNewSession(qq422016 qtio422016.Writer) {
//line view/page/new_session.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/page/new_session.qtpl:5
	StreamNewSession(qw422016)
//line view/page/new_session.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line view/page/new_session.qtpl:5
}

//line view/page/new_session.qtpl:5
func NewSession() string {
//line view/page/new_session.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line view/page/new_session.qtpl:5
	WriteNewSession(qb422016)
//line view/page/new_session.qtpl:5
	qs422016 := string(qb422016.B)
//line view/page/new_session.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line view/page/new_session.qtpl:5
	return qs422016
//line view/page/new_session.qtpl:5
}

//line view/page/new_session.qtpl:7
func streamsessionForm(qw422016 *qt422016.Writer) {
//line view/page/new_session.qtpl:7
	qw422016.N().S(`
  <form action="/login" method="POST">
    <div class="pt-1">
      `)
//line view/page/new_session.qtpl:10
	partial.StreamSubHeading(qw422016, "Login")
//line view/page/new_session.qtpl:10
	qw422016.N().S(`
      `)
//line view/page/new_session.qtpl:11
	partial.StreamTextInput(qw422016, "username", "username", "Username")
//line view/page/new_session.qtpl:11
	qw422016.N().S(`
      `)
//line view/page/new_session.qtpl:12
	partial.StreamPasswordInput(qw422016, "password", "password", "Password")
//line view/page/new_session.qtpl:12
	qw422016.N().S(`
      `)
//line view/page/new_session.qtpl:13
	partial.StreamSubmitButton(qw422016, "Login")
//line view/page/new_session.qtpl:13
	qw422016.N().S(`
    </div>
  </form>
`)
//line view/page/new_session.qtpl:16
}

//line view/page/new_session.qtpl:16
func writesessionForm(qq422016 qtio422016.Writer) {
//line view/page/new_session.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/page/new_session.qtpl:16
	streamsessionForm(qw422016)
//line view/page/new_session.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line view/page/new_session.qtpl:16
}

//line view/page/new_session.qtpl:16
func sessionForm() string {
//line view/page/new_session.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line view/page/new_session.qtpl:16
	writesessionForm(qb422016)
//line view/page/new_session.qtpl:16
	qs422016 := string(qb422016.B)
//line view/page/new_session.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line view/page/new_session.qtpl:16
	return qs422016
//line view/page/new_session.qtpl:16
}
