// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CreateConfig is an autogenerated mock type for the CreateConfig type
type CreateConfig struct {
	mock.Mock
}

// JWTSecret provides a mock function with given fields:
func (_m *CreateConfig) JWTSecret() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RootPath provides a mock function with given fields:
func (_m *CreateConfig) RootPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
