default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: markit_development

test:
  <<: *default
  database: markit_test

production:
  <<: *default
  database: markit_production
  username: markit
  password: <%= ENV['MARKIT_DATABASE_PASSWORD'] %>
