// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthConfig is an autogenerated mock type for the AuthConfig type
type AuthConfig struct {
	mock.Mock
}

// JWTSecret provides a mock function with given fields:
func (_m *AuthConfig) JWTSecret() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoginPath provides a mock function with given fields:
func (_m *AuthConfig) LoginPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
