// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnauthConfig is an autogenerated mock type for the UnauthConfig type
type UnauthConfig struct {
	mock.Mock
}

// JWTSecret provides a mock function with given fields:
func (_m *UnauthConfig) JWTSecret() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RootPath provides a mock function with given fields:
func (_m *UnauthConfig) RootPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
