// Code generated by qtc from "new_session.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/new_session.qtpl:1
package view

//line view/new_session.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/new_session.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/new_session.qtpl:1
func StreamNewSession(qw422016 *qt422016.Writer) {
//line view/new_session.qtpl:1
	qw422016.N().S(`
  <div class="max-w-sm mx-auto flex flex-col p-6 bg-white rounded-lg shadow-lg mt-16">
    <form action="/login" method="POST">
      <div class="pt-1">
        <h3 class="text-3xl text-gray-900 font-light mb-3 mt-3">Login</h4>
        <input type="text" name="username" id="username" class="text-2xl font-light border rounded-sm shadow-inner w-full p-2 mb-3" placeholder="Username" />
        <input type="password" name="password" id="password" class="text-2xl font-light border rounded-sm shadow-inner w-full p-2 mb-2" placeholder="Password" />
        <input type="submit" class="bg-blue-500 hover:bg-blue-600 hover:shadow-inner text-white font-bold font-mono w-full p-4 mt-2 rounded-sm shadow" value="Login" />
      </div>
    </form>
  </div>
`)
//line view/new_session.qtpl:12
}

//line view/new_session.qtpl:12
func WriteNewSession(qq422016 qtio422016.Writer) {
//line view/new_session.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/new_session.qtpl:12
	StreamNewSession(qw422016)
//line view/new_session.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line view/new_session.qtpl:12
}

//line view/new_session.qtpl:12
func NewSession() string {
//line view/new_session.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line view/new_session.qtpl:12
	WriteNewSession(qb422016)
//line view/new_session.qtpl:12
	qs422016 := string(qb422016.B)
//line view/new_session.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line view/new_session.qtpl:12
	return qs422016
//line view/new_session.qtpl:12
}
